name: ksz-lae-xcorr
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - astropy
  - matplotlib
  - pyyaml
  - gsl          # system dep required by 21cmFAST's C backend
  - fftw         # system dep required by 21cmFAST's C backend
  - pip
  - pip:
      - git+https://github.com/21cmFAST/21cmFAST.git@54a215398
      - camb
      - pytest
