#!/usr/bin/env python3
"""
scripts/22_ksz_auto_power_plot.py
====================================
Plots the kSZ-related auto-power spectra (kSZ, kSZ^2, xe^2, v^2, v_proj,
v_proj^2) already sitting in data/products/auto_results.pkl -- computed
by correlation.auto_power.compute_auto_spectra (called from scripts/04),
never independently visualized before. Evaluated at a SINGLE reference
redshift (box midpoint) -- this is NOT a z-sweep, unlike
scripts/21's tracer auto-power. Purpose: a basic "is this smooth" sanity
check on the kSZ side, per Girish's suggestion (2026-09-18) to validate
simpler ingredients before chasing the full cross-correlation.

IMPORTANT CAVEAT: unlike scripts/21's tracer auto-power (which is
independent of the stitching bug), these ARE built from the stitched
kSZ/velocity/xHI fields -- the same pathway known to be unstable. A
smooth result here would be somewhat reassuring; a jagged/garbage result
would be consistent with (though not by itself proof of) the known bug.

Make sure auto_results.pkl is CURRENT before running this -- it is
regenerated by scripts/04, and a stale copy from before the velocity fix
or the LAE/LBG checkpoint fix will silently show pre-fix numbers.

Usage:
    python scripts/22_ksz_auto_power_plot.py
"""

import argparse
import datetime
import os
import pickle
import sys

import matplotlib
import numpy as np

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from ksz_lae_xcorr.correlation.power_spectra import KGrid, ell_at_redshift
from ksz_lae_xcorr.utils.config import load_config
from ksz_lae_xcorr.utils.figio import compute_symlog_linthresh, save_fig

MAP_NAMES = ["kSZ", "kSZ2", "xe2", "v2", "v_proj", "v_proj2"]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=str, default="configs/fiducial.yaml")
    parser.add_argument("--auto-results", type=str, default=None,
                         help="Path to auto_results.pkl (default: cfg.paths.products_root/auto_results.pkl)")
    parser.add_argument("--out-dir", type=str, default="paper/figure_scripts/output")
    args = parser.parse_args()

    cfg = load_config(args.config)
    os.makedirs(args.out_dir, exist_ok=True)

    auto_path = args.auto_results or os.path.join(cfg.paths.products_root, "auto_results.pkl")
    print(f"Loading: {auto_path}")
    mtime = os.path.getmtime(auto_path)
    print(f"  Last modified: {datetime.datetime.fromtimestamp(mtime)} -- "
          f"confirm this is AFTER your most recent scripts/04 rerun before trusting these numbers.")

    with open(auto_path, "rb") as f:
        auto_results = pickle.load(f)

    kg = KGrid(cfg)
    z_ref = 0.5 * (cfg.box.z_min + cfg.box.z_max)
    ell = ell_at_redshift(cfg, kg, z_ref)
    print(f"  Reference redshift (box midpoint): z={z_ref:.2f}")

    fig, axes = plt.subplots(2, 3, figsize=(15, 9), constrained_layout=True)
    for ax, map_name in zip(axes.flat, MAP_NAMES):
        if map_name not in auto_results:
            ax.set_title(f"{map_name} -- not in auto_results.pkl")
            continue

        seeds = sorted(auto_results[map_name].keys())
        D_stack = np.array([auto_results[map_name][s][0] for s in seeds])
        D_mean = np.nanmean(D_stack, axis=0)
        D_std = np.nanstd(D_stack, axis=0) if len(seeds) > 1 else np.zeros_like(D_mean)

        n_nan = np.sum(np.isnan(D_stack))
        if n_nan:
            print(f"  {map_name}: {n_nan}/{D_stack.size} values are NaN across all seeds/bins")

        ax.errorbar(ell, D_mean, yerr=D_std, fmt="o-", capsize=3, color="darkblue")
        linthresh = compute_symlog_linthresh(D_mean)
        ax.set_yscale("symlog", linthresh=linthresh)
        ax.set_xscale("log")
        ax.axhline(0, color="gray", lw=0.5)
        ax.set_xlabel(r"$\ell$")
        ax.set_ylabel(r"$D_\ell$ (symlog)")
        ax.set_title(f"{map_name} auto-power ({len(seeds)} seeds, z={z_ref:.1f})")

    fig.suptitle("kSZ-related auto-power spectra (single reference z -- box midpoint)", fontsize=13)
    outpath = os.path.join(args.out_dir, "ksz_auto_power_overview.pdf")
    save_fig(fig, outpath)
    plt.close(fig)
    print(f"\nSaved: {outpath} (+ .png)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
